//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES
{
    using System;
    using System.Collections.Generic;
    
    public partial class 결산자료
    {
        public int No { get; set; }
        public string 계정과목 { get; set; }
        public Nullable<long> 차변금액 { get; set; }
        public Nullable<long> 대변금액 { get; set; }
        public Nullable<long> 분개대상금액 { get; set; }
        public System.DateTime 결산기간 { get; set; }
        public Nullable<int> 결산자료No { get; set; }
    }
}
