//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES
{
    using System;
    using System.Collections.Generic;
    
    public partial class 생산검사
    {
        public string 생산검사번호 { get; set; }
        public string 생산실적번호 { get; set; }
        public string 검사유형번호 { get; set; }
        public int 양품수량 { get; set; }
        public int 불량수량 { get; set; }
    
        public virtual 검사유형 검사유형 { get; set; }
        public virtual 생산실적현황 생산실적현황 { get; set; }
    }
}
